server:
  port: 8001

# 继承service父模块的数据库依赖，所以autoconfiguration总是会报错
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html