server:
  port: 8001

# 继承service父模块的数据库依赖，所以autoconfiguration总是会报错
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  main:
    allow-bean-definition-overriding: true #允许bean的覆盖: feign-clients/product/两个feign client配置集中在一个重名的bean中：service-product.FeignClientSpecification