server:
  port: 13000

# 继承service父模块的数据库依赖，所以autoconfiguration总是会报错
spring:
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
