server:
  port: 8002

# 继承service父模块的数据库依赖，所以autoconfiguration总是会报错
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  redis:
    host: 192.168.241.188
    port: 6379
#    password:


gmall:
  threadpool:
    core-pool-size: 8
    maximum-pool-size: 24
    keep-alive-time: 5 #单位由线程池的参数TimeUnit unit决定，见MyThreadPoolAutoConfiguration
    work-queue-size: 3000
